version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - mysql_data:/var/lib/mysql

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_container
    restart: always
    volumes:
      - ./app:/app
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password

volumes:
  mysql_data:
